version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://user:password@db/service_db
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  test:
    build: .
    command: python3 -m unittest discover -s tests
    environment:
      DATABASE_URL: postgresql://user:password@db/service_db
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis
      
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: service_db

volumes:
  postgres_data: