version: '3.8'

services:
  api:
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      ETHERSCAN_API_KEY: ""
      DATABASE_URL: postgresql://user:password@db/service_db
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: service_db

volumes:
  postgres_data: